# Generated by Django 4.0.1 on 2022-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('cty', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('cnty', models.CharField(max_length=100)),
            ],
        ),
    ]
